language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-logstash.gemspec
- gem install sensu-plugins-logstash-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: A8VJqKT9nenXREnLIJUTGhrvmIF4BYsJVyt/Fuy5JJxsFRP53RV2YLWruQfDq6rR9UgjPq43AEI8zJ7wL5WqISDCe/lDcai5kKbuewFr0Uex/d8ZeIgKMGZw+1+NI4x2KHXg9CiIbfVQWgivv5hd8U/F/qI02rXBu5xTE+7epnk=
  gem: sensu-plugins-logstash
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    repo: sensu-plugins/sensu-plugins-logstash
